basePath: /
definitions:
  models.ShortURL:
    properties:
      clicks:
        type: integer
      code:
        type: string
      created_at:
        type: string
      original_url:
        type: string
    type: object
  models.URLRequest:
    properties:
      url:
        type: string
    required:
    - url
    type: object
  models.URLResponse:
    properties:
      original_url:
        type: string
      short_code:
        type: string
      short_url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: URL Shortener REST API project
  title: URL Shortener API
  version: "1.0"
paths:
  /{code}:
    get:
      description: Redirecting from shorted URL
      parameters:
      - description: Short code
        in: path
        name: code
        required: true
        type: string
      responses:
        "302":
          description: Found
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Redirect
      tags:
      - urls
  /health:
    get:
      description: Checking API and services working
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check API
      tags:
      - health
  /info/{code}:
    get:
      description: Showing information about URL
      parameters:
      - description: Short code
        in: path
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ShortURL'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Info
      tags:
      - urls
  /shorten:
    post:
      consumes:
      - application/json
      description: Creating a new short url
      parameters:
      - description: URL payload
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.URLRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.URLResponse'
      summary: Creating short url
      tags:
      - urls
swagger: "2.0"
